package edge

type COREWEBVIEW2_DOWNLOAD_STATE uint32

const (
	COREWEBVIEW2_DOWNLOAD_STATE_IN_PROGRESS COREWEBVIEW2_DOWNLOAD_STATE = 0
	COREWEBVIEW2_DOWNLOAD_STATE_INTERRUPTED COREWEBVIEW2_DOWNLOAD_STATE = 1
	COREWEBVIEW2_DOWNLOAD_STATE_COMPLETED   COREWEBVIEW2_DOWNLOAD_STATE = 2
)
