package edge

type COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON uint32

const (
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NONE                           COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 0
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_FAILED                    COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 1
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_ACCESS_DENIED             COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 2
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_NO_SPACE                  COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 3
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_NAME_TOO_LONG             COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 4
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TOO_LARGE                 COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 5
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_MALICIOUS                 COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 6
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TRANSIENT_ERROR           COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 7
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_BLOCKED_BY_POLICY         COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 8
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_SECURITY_CHECK_FAILED     COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 9
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_TOO_SHORT                 COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 10
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_FILE_HASH_MISMATCH             COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 11
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_FAILED                 COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 12
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_TIMEOUT                COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 13
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_DISCONNECTED           COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 14
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_SERVER_DOWN            COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 15
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_NETWORK_INVALID_REQUEST        COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 16
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_FAILED                  COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 17
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_NO_RANGE                COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 18
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_BAD_CONTENT             COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 19
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_UNAUTHORIZED            COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 20
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CERTIFICATE_PROBLEM     COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 21
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_FORBIDDEN               COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 22
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_UNEXPECTED_RESPONSE     COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 23
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CONTENT_LENGTH_MISMATCH COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 24
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_SERVER_CROSS_ORIGIN_REDIRECT   COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 25
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_CANCELED                  COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 26
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_SHUTDOWN                  COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 27
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_USER_PAUSED                    COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 28
	COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON_DOWNLOAD_PROCESS_CRASHED       COREWEBVIEW2_DOWNLOAD_INTERRUPT_REASON = 29
)
